name: Build Go Agent

on:
  push:
    paths:
      - 'agent-go/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux]
        goarch: [amd64, arm64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Build
        run: |
          cd agent-go
          mkdir -p dist
          GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/agent-${{ matrix.goos }}-${{ matrix.goarch }} main.go

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: agent-binaries
          path: agent-go/dist/*